### ISSUE TITLE
How do i get the sound to play through my mic?

### ISSUE THREAD

**Issue by Tytan-Codes** [PhoenixWyllow/Soundboard4MacroDeck2#33]
How do i get the sound to play through my mic?

**Comment by Gilsaaa** [comment]
Did you manage to make it work? Also having the same issue

**Comment by PhoenixWyllow** [comment]
Due to the nature of how "output" devices work vs "inputs" in the NAudio library the simple answer is no.
I will keep looking into if it is possible, but not something that's planned at this time. 

Soundpad provides this funcionality though other means (a VBAudio cable driver that's installed with Soundpad) - I have a plugin for that already. 
It can also be done through configuration of Voicemeeter (another VB product) and optionally installing VBCable indipendently.
