### ISSUE TITLE
Play behaviour

### ISSUE THREAD

**Issue by SuchByte** [PhoenixWyllow/Soundboard4MacroDeck2#5]
Users should have the possibility to choose between multiple play behaviours:
- "Play/Stop" -> On the first tap of the button, the audio starts playing, on the second tap it stops.
- "Play/Overlap" -> The audio overlaps on multiple taps
- "Play/Play again" -> On the first tap of the button, the audio starts playing, on the second tap it starts from the beginning.
- "Loop/Stop" -> On the first tap of the button, the audio starts playing and automatically loops, on the second tap it stops.

**Comment by PhoenixWyllow** [comment]
Notes:
- All actions except "Overlap" will stop all other audio from the plugin (this is necessary otherwise they all overlap)
- Play/play again functionality is essentially the action implemented since the first version

Changes will be merged soon. New labels are present - I have removed some because redundant.
