### ISSUE TITLE
error in import files from local

### ISSUE THREAD

**Issue by Roloman2810** [PhoenixWyllow/Soundboard4MacroDeck2#50]
**Describe the bug**
This pop continue pop in...
![img](https://i.imgur.com/zAtZfVB.png])

**To Reproduce**
1. Go to Audio file configuration.
2. Click on add file, select file from local.
3. See error

**Expected behavior**
Add sound, add volume, add class and hit 'ok'.

**Screenshots**
![img](https://i.imgur.com/zAtZfVB.png)

**Desktop (please complete the following information):**
 - OS: WIN 10
 - Browser: Chome
 - Version 2.0.3

Comment: Before this issue i had many local files and works perfect, i had reinstall Macro Deck because i uninstall it by miss click. reinstall the new version and cant make it work by this pop issue.

Edit: changed image tags to markdown (PhoenixWyllow)

**Comment by PhoenixWyllow** [comment]
You have two options right now:
1. add a category first (even just one called "Default"), then add your audio files.
2. since you only have one audio file, you can delete the soundboard.db file in `%APPDATA%/Macro Deck\plugins\PhoenixWyllow.Soundboard4MacroDeck\DB`. Then restart Macro Deck (the file will be recreated with the fixes in v2.0.3)

**Comment by Roloman2810** [comment]
Works Perfect, tnx
